// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6nqvLTjC-7_Sh_nFVbfUn0VrrOyfRUUA',
    appId: '1:328099288356:web:4b0f068f94875a05234fb1',
    messagingSenderId: '328099288356',
    projectId: 'abubakar-porfolio',
    authDomain: 'abubakar-porfolio.firebaseapp.com',
    storageBucket: 'abubakar-porfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcsUyjok2FiaI6cMYXRXw_XRcfu04xF_c',
    appId: '1:328099288356:android:ef2e495aba0b67d9234fb1',
    messagingSenderId: '328099288356',
    projectId: 'abubakar-porfolio',
    storageBucket: 'abubakar-porfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnG9htkYxjqZ6ADL5JbV4E6-YWi3pK7oA',
    appId: '1:328099288356:ios:bb8970e69f870020234fb1',
    messagingSenderId: '328099288356',
    projectId: 'abubakar-porfolio',
    storageBucket: 'abubakar-porfolio.firebasestorage.app',
    iosBundleId: 'com.example.weather',
  );
}
